### ISSUE TITLE
ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by SimonF89** [huggingface/neuralcoref#260] opened 2020-06-18 23:54 UTC
I get the following error while loading a custom mode with:
```
...
neuralcoref.add_to_pipe(nlp)
```

```
model in init = True
 ExtraData: unpack(b) received extra data. 
---------------------------------------------------------------------------
ExtraData                                 Traceback (most recent call last)
<ipython-input-6-3f11485ad4f8> in <module>
----> 1 neuralcoref.add_to_pipe(nlp)

/workspace/neuralcoref_02/neuralcoref_with_training_mods/neuralcoref/__init__.py in add_to_pipe(nlp, **kwargs)
     40 
     41 def add_to_pipe(nlp, **kwargs):
---> 42     coref = NeuralCoref(nlp.vocab, **kwargs)
     43     nlp.add_pipe(coref, name="neuralcoref")
     44     return nlp

neuralcoref.pyx in neuralcoref.neuralcoref.NeuralCoref.__init__()

neuralcoref.pyx in neuralcoref.neuralcoref.NeuralCoref.from_disk()

/opt/conda/lib/python3.6/site-packages/thinc/neural/_classes/model.py in from_bytes(self, bytes_data)
    353 
    354     def from_bytes(self, bytes_data):
--> 355         data = srsly.msgpack_loads(bytes_data)
    356         weights = data[b"weights"]
    357         queue = [self]

/opt/conda/lib/python3.6/site-packages/srsly/_msgpack_api.py in msgpack_loads(data, use_list)
     27     # msgpack-python docs suggest disabling gc before unpacking large messages
     28     gc.disable()
---> 29     msg = msgpack.loads(data, raw=False, use_list=use_list)
     30     gc.enable()
     31     return msg

/opt/conda/lib/python3.6/site-packages/srsly/msgpack/__init__.py in unpackb(packed, **kwargs)
     58         object_hook = kwargs.get('object_hook')
     59         kwargs['object_hook'] = functools.partial(_decode_numpy, chain=object_hook)
---> 60     return _unpackb(packed, **kwargs)
     61 
     62 

_unpacker.pyx in srsly.msgpack._unpacker.unpackb()

ExtraData: unpack(b) received extra data.
```

Thats how my model-folder looks like.

![image](https://user-images.githubusercontent.com/8984410/85082651-da7a0d80-b1cf-11ea-9c95-e9e2677e8cce.png)

the model was generated as explained below (see mail from **chieter**).

**Comment by svlandeg** [comment] 2020-06-19 08:04
Could you post the code you run when this error is thrown, and details on how you installed neuralcoref and spacy?

**Comment by EricLe-dev** [comment] 2020-06-19 08:07
@svlandeg I think he encountered this error while trying to load a new trained model. Currently, we all having this problem, can you please give us an instruction to load a new trained model (trained by neuralcoref) using the `add_to_pipe` function? 
Thank you!

**Comment by snape6666** [comment] 2020-06-19 11:59
yes please!^^ We are already on the verge of developing a new model, because we have already wasted so much time with the German model.

**Comment by svlandeg** [comment] 2020-06-19 12:13
I understand you are frustrated, but please consider that it is very difficult for us to follow up on user's issues when only presented with a raw stack trace, no example code or software/model versions, and phrasings like "we all having this problem".

We need some more context - but please stick to the specific issue in each thread. Let's try to keep the discussion focused on one issue at the time, or it simply gets too complicated to address.

@snape6666 : which versions of neuralcoref, spacy and `de_core_news_md` are you using? Have you recently upgraded to spacy v.2.3? Did you upgrade the model as well? Was this working on 2.2.3 or not?

**Comment by snape6666** [comment] 2020-06-19 12:16
For this test i was using spacy 2.1.0 with the 2.1.0 model. neuralcoref in the newest version.

**Comment by EricLe-dev** [comment] 2020-06-19 12:20
[This](https://github.com/huggingface/neuralcoref/issues/255#issuecomment-637480428) was the step that a friendly guy did and also the way I trained my Dutch model this way. 
For you @snape6666, I think you are not alone as [this guy](https://stackoverflow.com/questions/60243313/how-do-you-use-a-custom-neuralcoref-model-in-spacy) already posted this question with exactly the same error.

Can you please share with me maybe the way you did to export the trained model to this?
![image](https://user-images.githubusercontent.com/46409458/85131891-edd5b900-b261-11ea-87d2-9667efd72f62.png)

**Comment by svlandeg** [comment] 2020-06-19 12:27
Hi @EricLe-dev : please, it is becoming increasingly difficult to follow the thread of an issue as you're constantly mixing in your specific questions and problems in other's threads. Please also stop pinging maintainers as this makes our GH mentions really hard to use.

**Comment by snape6666** [comment] 2020-06-19 12:28
Hi svlandeg,
his questions are related to my problem. My students are just summarizing how we created our model. I agree with EricLe-dev that the error is in the model generation and therefore it does not load properly. The answer should come in the next few minutes.

**Comment by svlandeg** [comment] 2020-06-19 12:29
> 
> 
> For this test i was using spacy 2.1.0 with the 2.1.0 model. neuralcoref in the newest version.
@snape6666 
 
> the englisch Model loads fine. But when i try to load my self trained model, it throws this error.

So the error gets thrown with a model you've trained and stored to disk? Not with `de_core_news_md` ?

**Comment by snape6666** [comment] 2020-06-19 12:30
yes!! the de_core_news_md works fine! Its the self trained neuralcoref model

**Comment by svlandeg** [comment] 2020-06-19 12:32
I asked you to produce a code snippet that throws the error, and you gave one with `de_core_news_md`. Then it turns out, that is not the problem. I'm sorry, but I really can't try and reproduce your error like this.

**Comment by chieter** [comment] 2020-06-19 12:33
I think the error is a result of using the wrong data in the neuralcoref_cache. We did the following to extract the model and save it to disk: 

> 1. Install the alpha version of thinc, as this version includes the PyTorchWrapper
> 2. Create an Instance of the model in a python shell. I basically used the same instantiation that is >used in train/dataset.py: `from neuralcoref.train.model import Model`
>`model = Model(len(voc), SIZE_EMBEDDING, Args.h1, Args.h2, Args.h3, SIZE_PAIR_IN, >SIZE_SINGLE_IN)`
>Adjust the parameters according to the ones you used during traininig.
>3. Load the model checkpoint you want to use: >`model.load_state_dict(torch.load(path_to_checkpoint_file))` You can find this in train/learn.py.
>4. If everything worked so far you should see a message, that all keys could be matched and if you >call the model, you should see  different parts of the net labeled (word_embeds), (drop), (pair_top) >and (single_top).
>5. As far as I could tell the (pair_top) and (single_top) parts are used in the model that is loaded >from neuralcoref cache. I think to avoid exporting the  dropout layers used in training you need to >change the model to evaluation mode using `model.eval()`
>6.You can now use the PyTorchWrapper from the thinc alpha. 
>`from thinc.api import PyTorchWrapper` 
>`pair_top_model = PyTorchWrapper(model.pair_top)`
>`single_top_model = PyTorchWrapper(model.single_top)`
>7. These models can now be written to disk using:
>`f = open('trained_pair_top_model', 'wb')`
>`f.write(pair_top_model.to_bytes())`
>`f.close()`

We then replaced the files in the neuralcoref_cache. As I stated in another issue I'm not sure if this is even the correct way of starting to replace the model used by neuralcoref.

**Comment by snape6666** [comment] 2020-06-19 12:34
> yes please!^^ We are already on the verge of developing a new model, because we have already wasted so much time with trying to fix loading our own German model.
> 
> The Code, with custom Model:
> 
> ```
> import de_core_news_md
> import logging;
> logging.basicConfig(level=logging.INFO)
> import neuralcoref
> INFO:neuralcoref:Loading model from /root/.ger_neuralcoref_cache/neuralcoref
> 
> nlp = spacy.load("de_core_news_md")
> neuralcoref.add_to_pipe(nlp)
> ```

as you see here my last line in the code is the neuralcoref.add_to_pipe(nlp)

Here i try to load the new model, and then i get the error shown in the first comment

**Comment by svlandeg** [comment] 2020-06-19 12:40
> Hi svlandeg,
> his questions are related to my problem. My students are just summarizing how we created our model (...) The reply of my students should come in the next few minutes.

Can you please clarify which github handles you are referring to? Who are your students? Are they all working on the same assignment?  
That helps me to follow the discussion.

**Comment by snape6666** [comment] 2020-06-19 12:44
Sorry for the confusion.
**chieter** is one oy my students.

**Comment by svlandeg** [comment] 2020-06-19 12:46
Ok, good to know. And by `the alpha version of thinc`, you mean thinc 8?

**Comment by chieter** [comment] 2020-06-19 12:49
Yes, I used `pip install thinc==8.0.0a1` .

**Comment by svlandeg** [comment] 2020-06-19 12:56
Ok. Unfortunately, Thinc 8 and spaCy 2 aren't compatible. We're currently working on a major release spaCy v.3 which will use thinc 8. A lot of the internals are different and not backwards compatible, so I couldn't imagine how this would ever work.

Due to the work on spaCy 3, we haven't had the bandwith to provide full support for neuralcoref. We do want to bring the code up-to-date with Thinc 8 and spaCy 3, but this will have to wait until we get a first release out for spaCy 3.

Also, just FYI, I haven't myself tried training a new model with neuralcoref, as I wasn't involved in the original development of this code base.

**Comment by chieter** [comment] 2020-06-19 13:02
Thanks for your reply :)
My colleague just informed me, that it is indeed unneccessary to use the thinc 8 version, as PyTorchWrapper is available in earlier releases but was relocated. So i mistakenly assumed it was added later. I will try to use an earlier version of thinc, maybe this will resolve some issues.
Best wishes to you! I'm looking forward to spacy v3 :)

**Comment by GregorLied** [comment] 2020-06-19 13:16
> I think the error is a result of using the wrong data in the neuralcoref_cache. We did the following to extract the model and save it to disk:
> 
> > 1. Install the alpha version of thinc, as this version includes the PyTorchWrapper
> > 2. Create an Instance of the model in a python shell. I basically used the same instantiation that is >used in train/dataset.py: `from neuralcoref.train.model import Model`
> >    `model = Model(len(voc), SIZE_EMBEDDING, Args.h1, Args.h2, Args.h3, SIZE_PAIR_IN, >SIZE_SINGLE_IN)`
> >    Adjust the parameters according to the ones you used during traininig.
> > 3. Load the model checkpoint you want to use: >`model.load_state_dict(torch.load(path_to_checkpoint_file))` You can find this in train/learn.py.
> > 4. If everything worked so far you should see a message, that all keys could be matched and if you >call the model, you should see  different parts of the net labeled (word_embeds), (drop), (pair_top) >and (single_top).
> > 5. As far as I could tell the (pair_top) and (single_top) parts are used in the model that is loaded >from neuralcoref cache. I think to avoid exporting the  dropout layers used in training you need to >change the model to evaluation mode using `model.eval()`
> >    6.You can now use the PyTorchWrapper from the thinc alpha.
> >    `from thinc.api import PyTorchWrapper`
> >    `pair_top_model = PyTorchWrapper(model.pair_top)`
> >    `single_top_model = PyTorchWrapper(model.single_top)`
> > 6. These models can now be written to disk using:
> >    `f = open('trained_pair_top_model', 'wb')`
> >    `f.write(pair_top_model.to_bytes())`
> >    `f.close()`
> 
> We then replaced the files in the neuralcoref_cache. As I stated in another issue I'm not sure if this is even the correct way of starting to replace the model used by neuralcoref.

Thank you for taking your time and trying to understand the problem with us svlandeg! =)
We are sure that the error occurs because of the pairs_model and single_model.
The error actually occured also with earlier versions of thinc (e.g. 7.0.8).

Additionally to the described procedure of @chieter, we came up with the idea to create the required key2row and vectors file in the static_vectors folder and tuned_vectors folder respectively with the (command line command)[https://spacy.io/api/cli#init-model] and only moved the key2row and vectors file in the respective folders. 
In order to use that command we merged prior to that the ./neuralcoref/train/weights/tuned_word_embeddings.npy and ./neuralcoref/train/weights/static_word_vocabulary.txt in a text file with a similar structure to this
![Screen Shot 2020-06-19 at 21 05 02](https://user-images.githubusercontent.com/45819802/85135494-c2a69600-b270-11ea-8c09-8b9b07a765d5.png)
so we were able to apply that command. So far this isn't raising any errors though, but due to the previous mentioned ExtraData error, we weren't able to test our German NeuralCoref model yet. But maybe you can say, if this makes sense or not. 

Again, thank you very much for your great work with this package and for answering our questions.

**Comment by firasfrikha** [comment] 2020-07-08 14:06
> Thanks for your reply :)
> My colleague just informed me, that it is indeed unneccessary to use the thinc 8 version, as PyTorchWrapper is available in earlier releases but was relocated. So i mistakenly assumed it was added later. I will try to use an earlier version of thinc, maybe this will resolve some issues.
> Best wishes to you! I'm looking forward to spacy v3 :)

Hello,
which version of thinc have you used please, i couldn't find PytorchWrapper in earlier version

**Comment by firasfrikha** [comment] 2020-07-08 14:35
have anyone find a  solution to this error please ? 
I'am facing the same error after training my model

**Comment by firasfrikha** [comment] 2020-07-10 14:32
@chieter hello,
have succeded to load the model please ?

**Closed** 2022-04-17 06:47 UTC
Labels: wontfix, usage
